version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: pastebin_database
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5435:5432"
    
  app:
    build:
      context: .
    container_name: pastebin_app
    ports:
      - "80:80"
    depends_on:
      - db
    